apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eksargocd-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    name: eksargocd-eks-cluster-app
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.11.0
    helm:
      releaseName: external-secrets
      valuesObject:
        installCRDs: true
        serviceAccount:
          create: true
          name: external-secrets
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true