apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eksargocd-ingress-alb-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    name: eksargocd-eks-cluster-app
    
  project: default

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: aws-load-balancer-tls
      namespace: kube-system
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 3.5.0
    helm:
      releaseName: aws-load-balancer-controller
      valuesObject:
        enableShield: false
        enableWaf: false
        enableWafv2: false
        region: ap-northeast-1
        vpcTags:
          Name: eksargocd-vpc
        clusterName: eksargocd-eks-cluster-app
        serviceAccount:
          create: true
          name: aws-load-balancer-controller

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true