apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eksargocd-web-ap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app
    name: eksargocd-eks-cluster-app
  project: default
  source:
    path: base
    repoURL: https://github.com/ys-o/EKS-ArgoCD-Handson_Application_manifests
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true